extensions:
  - addsTo:
      pack: joern/java-all
      extensible: sinkModel
    data:
      - ["org.apache.commons.exec.environment", "EnvironmentUtils", True, "addVariableToEnvironment", "(Map,String)", "", "Argument[0]", "environment-injection", "manual"]